# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table='detail',
        ),
    ]
