# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180713_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_brand', models.CharField(max_length=40)),
                ('p_quantity', models.IntegerField()),
                ('p_price', models.IntegerField()),
                ('p_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
