# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180713_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_username', models.CharField(max_length=50)),
                ('m_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
