# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_csvdetail_customer_sale_saledetail_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Thing'),
        ),
    ]
