# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180723_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('time', models.TextField(default=None)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
