# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.TextField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
