# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.TextField(default=None),
        ),
    ]
