# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'imagetable',
            },
        ),
    ]
