# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_imagetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
