# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180726_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.TextField(),
        ),
    ]
